services:
    snoob_mailer.mailer.abstract:
        class: "Snoob\Component\Mailer\AbstractMailer"
        abstract: true
        calls:
            - [ "setParameters", [ "@snoob_mailer.parameters" ] ]
